version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: "-Dspring.devtools.restart.enabled=true -Dfile.encoding=UTF-8"
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://db/library
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Abcd1234!
    volumes:
      - .:/app
      - gradle-cache:/root/.gradle
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: library
      MYSQL_ROOT_PASSWORD: Abcd1234!
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
  gradle-cache: